// Builds the self-contained, ESM-free goja bundle from the TypeScript source.
//
// Output: goja/bundle.js — an IIFE targeting ES2015 (goja supports ES2020+, but
// ES2015 keeps the output free of any runtime-feature surprises), platform
// "neutral" so esbuild injects NO node/browser globals or `node:` builtins. The
// only globals the bundle touches are the ones the Go host injects
// (__db/__newId/__now) and standard JS (JSON/Math/RegExp).
//
// Run: `node goja/build.mjs`  (esbuild is the sole devDependency; see package.json)
// The built bundle.js is committed so hanzoai/cloud can go:embed it (embed.go),
// exactly how @hanzo/plans ships goja/bundle.js.

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

await build({
  entryPoints: [join(here, "src/index.ts")],
  bundle: true,
  format: "iife",
  target: "es2015",
  platform: "neutral",
  legalComments: "none",
  banner: {
    js:
      "// @hanzo/captable — goja bundle (GENERATED by goja/build.mjs; edit src/*.ts).\n" +
      "// Self-contained, ESM-free; runs in dop251/goja inside hanzoai/cloud (HIP-0106).",
  },
  outfile: join(here, "bundle.js"),
});

console.log("built goja/bundle.js");
